## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

In [2]:
# Read in the charity_data.csv. 
# ("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
csv_path = "/app/data/raw/charity_data.csv"
application_df = pd.read_csv(csv_path)

# Display the DataFrame
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()

# Display the unique value counts for each column
print(unique_values)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()

# Display the value counts 
print(application_type_counts)

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

# Set the cutoff value to 200 and create the list
application_types_to_replace = application_df['APPLICATION_TYPE'].value_counts()[
    application_df['APPLICATION_TYPE'].value_counts() < 200
].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_type_counts = application_df['CLASSIFICATION'].value_counts()
classification_type_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
# Show only classification_type_counts >= 1
# Temporarily show all rows for classification_type_counts >= 1
with pd.option_context('display.max_rows', None):
    print(classification_type_counts[classification_type_counts >= 1])

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
C2190        1
C4200        1
C2600        1
C5200        1
C1370        1
C1248        1
C6100        1
C1820        1
C1900        1
C1236        1
C3700        1
C2570        1
C1580        1
C1245        1
C2500        1
C1570        1
C1283        1
C2380        1
C1732        1
C1728        1
C2170        1
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
# Set the cutoff value to 1000 and create the list
classifications_to_replace = application_df['CLASSIFICATION'].value_counts()[
    application_df['CLASSIFICATION'].value_counts() < 1000
].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [21]:
# Save the updated DataFrame to a CSV file
application_df.to_csv('/app/data/raw/AlphabetSoupCharity_updated.csv', index=False)

In [10]:
# Confirm data types
application_df.dtypes

APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

# Preprocessing continued:

1. **Convert Categorical Data to Numeric**  
   Use `pd.get_dummies` to transform categorical columns into numeric columns.

2. **Split Data into Features and Target Arrays**  
   Separate the independent variables (features) `X` from the dependent variable (target) `y`.

3. **Split Data into Training and Testing Datasets**  
   Use the `train_test_split` method to divide the preprocessed data into training (`X_train`, `y_train`) and testing sets (`X_test`, `y_test`)
   for model evaluation.

In [11]:
# Make a copy of application_df
application_df_copy = application_df.copy()

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
category_columns = ['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 
                    'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']

application_df_copy = pd.get_dummies(application_df, columns=category_columns)

# Show updated dummies df
application_df_copy.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [22]:
# Save a dummies DataFrame to a CSV file
application_df_copy.to_csv('/app/data/processed/AlphabetSoupCharity_dummies.csv', index=False)

In [14]:
# Split our preprocessed data into our features and target arrays
X = application_df_copy.drop(columns=['IS_SUCCESSFUL'])
y = application_df_copy['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
def create_model():
    nn = tf.keras.models.Sequential()
    # First hidden layer
    nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=X_train_scaled.shape[1]))
    # Second hidden layer
    nn.add(tf.keras.layers.Dense(units=30, activation='relu'))
    # Output layer
    nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    return nn

# Create the model
nn_model = create_model()

# Check the structure of the model
nn_model.summary()

/usr/local/lib/python3.9/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 80)             │         8,720 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,181 (43.68 KB)

 Trainable params: 11,181 (43.68 KB)

 Non-trainable params: 0 (0.00 B)

In [17]:
# Compile the model
nn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [18]:
# Train the model aka Fit the model to the training data
fit_model = nn_model.fit(X_train_scaled, y_train, 
                     epochs=100, batch_size=32, 
                     validation_split=0.2)

Epoch 1/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7088 - loss: 0.5942 - val_accuracy: 0.7215 - val_loss: 0.5651
Epoch 2/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7342 - loss: 0.5499 - val_accuracy: 0.7236 - val_loss: 0.5698
Epoch 3/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7380 - loss: 0.5438 - val_accuracy: 0.7186 - val_loss: 0.5678
Epoch 4/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7346 - loss: 0.5451 - val_accuracy: 0.7221 - val_loss: 0.5659
Epoch 5/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7401 - loss: 0.5410 - val_accuracy: 0.7232 - val_loss: 0.5645
Epoch 6/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7362 - loss: 0.5404 - val_accuracy: 0.7191 - val_loss: 0.5650
Epoch 7/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7341 - loss: 0.5440 - val_accuracy: 0.7238 - val_loss: 0.5647
Epoch 8/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7373 - loss: 0.5409 - val_accuracy: 0.7236 - val_loss: 0.5639
Epoch 9/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7357 - loss: 0.5430 - val_accuracy: 0.7213 - val_loss: 0.5623
Epoch 10/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7371 - loss: 0.5424 - val_accuracy: 0.7188 - val_loss: 0.5682
Epoch 11/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7364 - loss: 0.5431 - val_accuracy: 0.7217 - val_loss: 0.5637
Epoch 12/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7393 - loss: 0.5367 - val_accuracy: 0.7254 - val_loss: 0.5639
Epoch 13/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7413 - loss: 0.5335 - val_accuracy: 0.7234 - val_loss: 0.5621
Epoch 14/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7374 - loss: 0.5400 - val_accuracy: 0.7219 - val_loss: 0.5634
Epoch 15/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7397 - loss: 0.5382 - val_accuracy: 0.7228 - val_loss: 0.5642
Epoch 16/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7416 - loss: 0.5357 - val_accuracy: 0.7221 - val_loss: 0.5634
Epoch 17/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7412 - loss: 0.5336 - val_accuracy: 0.7234 - val_loss: 0.5629
Epoch 18/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7445 - loss: 0.5313 - val_accuracy: 0.7226 - val_loss: 0.5629
Epoch 19/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7388 - loss: 0.5348 - val_accuracy: 0.7250 - val_loss: 0.5641
Epoch 20/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7404 - loss: 0.5386 - val_accuracy: 0.7254 - val_loss: 0.5634
Epoch 21/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7397 - loss: 0.5361 - val_accuracy: 0.7248 - val_loss: 0.5628
Epoch 22/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7409 - loss: 0.5334 - val_accuracy: 0.7226 - val_loss: 0.5629
Epoch 23/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 988us/step - accuracy: 0.7374 - loss: 0.5371 - val_accuracy: 0.7252 - val_loss: 0.5649
Epoch 24/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 974us/step - accuracy: 0.7436 - loss: 0.5322 - val_accuracy: 0.7242 - val_loss: 0.5633
Epoch 25/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7471 - loss: 0.5270 - val_accuracy: 0.7277 - val_loss: 0.5644
Epoch 26/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7446 - loss: 0.5315 - val_accuracy: 0.7252 - val_loss: 0.5624
Epoch 27/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7396 - loss: 0.5363 - val_accuracy: 0.7236 - val_loss: 0.5610
Epoch 28/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7501 - loss: 0.5246 - val_accuracy: 0.7261 - val_loss: 0.5641
Epoch 29/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 974us/step - accuracy: 0.7431 - loss: 0.5302 - val_accuracy: 0.7273 - val_loss: 0.5643
Epoch 30/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7502 - loss: 0.5217 - val_accuracy: 0.7238 - val_loss: 0.5624
Epoch 31/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7487 - loss: 0.5282 - val_accuracy: 0.7236 - val_loss: 0.5636
Epoch 32/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7468 - loss: 0.5278 - val_accuracy: 0.7256 - val_loss: 0.5632
Epoch 33/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7398 - loss: 0.5361 - val_accuracy: 0.7224 - val_loss: 0.5660
Epoch 34/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7430 - loss: 0.5314 - val_accuracy: 0.7236 - val_loss: 0.5667
Epoch 35/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7472 - loss: 0.5273 - val_accuracy: 0.7269 - val_loss: 0.5651
Epoch 36/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 956us/step - accuracy: 0.7476 - loss: 0.5262 - val_accuracy: 0.7228 - val_loss: 0.5689
Epoch 37/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7416 - loss: 0.5336 - val_accuracy: 0.7242 - val_loss: 0.5676
Epoch 38/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7438 - loss: 0.5281 - val_accuracy: 0.7258 - val_loss: 0.5645
Epoch 39/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7481 - loss: 0.5257 - val_accuracy: 0.7236 - val_loss: 0.5680
Epoch 40/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7431 - loss: 0.5298 - val_accuracy: 0.7238 - val_loss: 0.5675
Epoch 41/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7427 - loss: 0.5309 - val_accuracy: 0.7230 - val_loss: 0.5697
Epoch 42/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7451 - loss: 0.5277 - val_accuracy: 0.7283 - val_loss: 0.5652
Epoch 43/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7457 - loss: 0.5306 - val_accuracy: 0.7263 - val_loss: 0.5683
Epoch 44/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7486 - loss: 0.5242 - val_accuracy: 0.7256 - val_loss: 0.5675
Epoch 45/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 958us/step - accuracy: 0.7418 - loss: 0.5308 - val_accuracy: 0.7269 - val_loss: 0.5700
Epoch 46/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7432 - loss: 0.5310 - val_accuracy: 0.7248 - val_loss: 0.5675
Epoch 47/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 953us/step - accuracy: 0.7444 - loss: 0.5277 - val_accuracy: 0.7259 - val_loss: 0.5733
Epoch 48/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7443 - loss: 0.5278 - val_accuracy: 0.7256 - val_loss: 0.5691
Epoch 49/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 949us/step - accuracy: 0.7422 - loss: 0.5351 - val_accuracy: 0.7232 - val_loss: 0.5680
Epoch 50/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7430 - loss: 0.5311 - val_accuracy: 0.7242 - val_loss: 0.5667
Epoch 51/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 966us/step - accuracy: 0.7483 - loss: 0.5263 - val_accuracy: 0.7252 - val_loss: 0.5720
Epoch 52/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 971us/step - accuracy: 0.7425 - loss: 0.5317 - val_accuracy: 0.7242 - val_loss: 0.5723
Epoch 53/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7451 - loss: 0.5282 - val_accuracy: 0.7246 - val_loss: 0.5682
Epoch 54/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7482 - loss: 0.5268 - val_accuracy: 0.7236 - val_loss: 0.5732
Epoch 55/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 983us/step - accuracy: 0.7445 - loss: 0.5273 - val_accuracy: 0.7190 - val_loss: 0.5744
Epoch 56/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7371 - loss: 0.5335 - val_accuracy: 0.7238 - val_loss: 0.5745
Epoch 57/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7458 - loss: 0.5285 - val_accuracy: 0.7221 - val_loss: 0.5718
Epoch 58/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7486 - loss: 0.5281 - val_accuracy: 0.7228 - val_loss: 0.5708
Epoch 59/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7442 - loss: 0.5261 - val_accuracy: 0.7221 - val_loss: 0.5691
Epoch 60/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7432 - loss: 0.5309 - val_accuracy: 0.7234 - val_loss: 0.5750
Epoch 61/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7402 - loss: 0.5300 - val_accuracy: 0.7242 - val_loss: 0.5741
Epoch 62/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7480 - loss: 0.5250 - val_accuracy: 0.7228 - val_loss: 0.5744
Epoch 63/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7411 - loss: 0.5314 - val_accuracy: 0.7230 - val_loss: 0.5735
Epoch 64/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7435 - loss: 0.5286 - val_accuracy: 0.7238 - val_loss: 0.5721
Epoch 65/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 965us/step - accuracy: 0.7411 - loss: 0.5322 - val_accuracy: 0.7217 - val_loss: 0.5775
Epoch 66/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 998us/step - accuracy: 0.7411 - loss: 0.5299 - val_accuracy: 0.7232 - val_loss: 0.5747
Epoch 67/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7445 - loss: 0.5285 - val_accuracy: 0.7256 - val_loss: 0.5775
Epoch 68/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 991us/step - accuracy: 0.7490 - loss: 0.5220 - val_accuracy: 0.7228 - val_loss: 0.5773
Epoch 69/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7477 - loss: 0.5251 - val_accuracy: 0.7224 - val_loss: 0.5767
Epoch 70/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7419 - loss: 0.5297 - val_accuracy: 0.7238 - val_loss: 0.5784
Epoch 71/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7463 - loss: 0.5257 - val_accuracy: 0.7244 - val_loss: 0.5787
Epoch 72/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7453 - loss: 0.5309 - val_accuracy: 0.7250 - val_loss: 0.5779
Epoch 73/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7427 - loss: 0.5271 - val_accuracy: 0.7250 - val_loss: 0.5777
Epoch 74/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7471 - loss: 0.5246 - val_accuracy: 0.7256 - val_loss: 0.5780
Epoch 75/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7469 - loss: 0.5226 - val_accuracy: 0.7226 - val_loss: 0.5809
Epoch 76/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7465 - loss: 0.5245 - val_accuracy: 0.7234 - val_loss: 0.5783
Epoch 77/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7490 - loss: 0.5217 - val_accuracy: 0.7230 - val_loss: 0.5746
Epoch 78/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7462 - loss: 0.5248 - val_accuracy: 0.7224 - val_loss: 0.5785
Epoch 79/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7460 - loss: 0.5271 - val_accuracy: 0.7236 - val_loss: 0.5775
Epoch 80/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7476 - loss: 0.5263 - val_accuracy: 0.7226 - val_loss: 0.5749
Epoch 81/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7445 - loss: 0.5266 - val_accuracy: 0.7246 - val_loss: 0.5743
Epoch 82/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 983us/step - accuracy: 0.7462 - loss: 0.5265 - val_accuracy: 0.7219 - val_loss: 0.5798
Epoch 83/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7456 - loss: 0.5287 - val_accuracy: 0.7215 - val_loss: 0.5813
Epoch 84/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7436 - loss: 0.5257 - val_accuracy: 0.7236 - val_loss: 0.5774
Epoch 85/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7519 - loss: 0.5215 - val_accuracy: 0.7244 - val_loss: 0.5809
Epoch 86/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 987us/step - accuracy: 0.7435 - loss: 0.5277 - val_accuracy: 0.7236 - val_loss: 0.5825
Epoch 87/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7472 - loss: 0.5255 - val_accuracy: 0.7250 - val_loss: 0.5766
Epoch 88/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 957us/step - accuracy: 0.7479 - loss: 0.5252 - val_accuracy: 0.7238 - val_loss: 0.5742
Epoch 89/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7491 - loss: 0.5231 - val_accuracy: 0.7234 - val_loss: 0.5794
Epoch 90/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7457 - loss: 0.5261 - val_accuracy: 0.7234 - val_loss: 0.5798
Epoch 91/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7533 - loss: 0.5167 - val_accuracy: 0.7232 - val_loss: 0.5787
Epoch 92/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7496 - loss: 0.5200 - val_accuracy: 0.7217 - val_loss: 0.5842
Epoch 93/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7435 - loss: 0.5283 - val_accuracy: 0.7226 - val_loss: 0.5819
Epoch 94/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7467 - loss: 0.5240 - val_accuracy: 0.7230 - val_loss: 0.5857
Epoch 95/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7485 - loss: 0.5221 - val_accuracy: 0.7226 - val_loss: 0.5808
Epoch 96/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7434 - loss: 0.5274 - val_accuracy: 0.7242 - val_loss: 0.5850
Epoch 97/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7457 - loss: 0.5230 - val_accuracy: 0.7226 - val_loss: 0.5851
Epoch 98/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7455 - loss: 0.5281 - val_accuracy: 0.7248 - val_loss: 0.5832
Epoch 99/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7411 - loss: 0.5290 - val_accuracy: 0.7232 - val_loss: 0.5834
Epoch 100/100
644/644 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7481 - loss: 0.5230 - val_accuracy: 0.7240 - val_loss: 0.5816

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - 725us/step - accuracy: 0.7265 - loss: 0.5668
Loss: 0.5668289065361023, Accuracy: 0.7265306115150452

In [20]:
# Export our model to HDF5 file
nn_model.save('/app/data/processed/AlphabetSoupCharity.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.